web_nha_tro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from signin import views as sign_in_views
from rooms import views as room_views
from room_post import views as post_views
from django.contrib.auth import views as auth_views
from home import views as home_view

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.homeView, name='home'),
    path('caredview/',views.caredView),
    # path('chat', include('chat.urls')),
    path('room/', room_views.SiteRoomView.as_view(), name='room'),
    path(r'room/<int:id>/', room_views.roomDetail, name='roomDetail'),
    path(r'room/postcmt/', room_views.roomDetails),
    path(r'profile/',room_views.postedRoom, name='posted'),
    path(r'phongtro/',room_views.phongtro),
    path(r'ccmn/',room_views.ccmn),
    path(r'nnc/',room_views.nnc),
    path(r'ccnc/',room_views.ccnc),
    path(r'hcm/',room_views.hcm),
    path(r'hn/',room_views.hn),
    path(r'hue/',room_views.hue),
    path(r'danang/',room_views.danang),
    path(r'cantho/',room_views.cantho),

    path('cared/',room_views.SiteCaredRoom.as_view(),name='cared rooms'),

    path(r'login/', sign_in_views.SiteLoginView.as_view(redirect_authenticated_user=True), name='login'),

    path('logout/', sign_in_views.logout, name='logout'),

    path(r'register/', sign_in_views.SiteRegisterView.as_view(), name='register'),
    path('post/', post_views.post, name='post'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from user.models import OwnerUser
from multiupload.fields import MultiFileField, MultiMediaField


# Create your models here.
class RoomType(models.Model):
    name = models.CharField(max_length=150, default='')
    amount_of_room_intype = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class KitchenChoice(models.IntegerChoices):
    PRIVATE = 0, 'Bếp riêng'
    PUBLIC = 1, 'Chung'
    UNABLE = 2, 'Không nấu ăn'


class Room(models.Model):
    owner = models.ForeignKey(OwnerUser, on_delete=models.CASCADE, default=5)

    title = models.CharField('Tieu de', max_length=150, blank=True)

    # These attitude are showed on top of post
    price = models.IntegerField('Gia phong', )
    area = models.IntegerField('Dien tich phong', )

    address = models.CharField('Dia chi', max_length=150, )
    nearby = models.TextField('Gan cac dia diem', max_length=300, )

    # Information of room
    type = models.ForeignKey(RoomType, on_delete=models.CASCADE, )

    chung_chu = models.BooleanField(default=False)
    private_bathroom = models.BooleanField('Nha ve sinh rieng', )
    co_nonglanh = models.BooleanField('Co nong lanh', )
    kitchen = models.IntegerField(
        choices=KitchenChoice.choices,
        default=0,
    )
    air_conditional = models.BooleanField('Dieu hoa')
    ban_cong = models.BooleanField('Ban cong')
    service_charge = models.TextField('Gia dich vu', max_length=100)
    other_ultily = models.TextField('Cac tien ich khac')
    update_at = models.DateTimeField(auto_now=True)

    # number of dates that post in active mode
    longevity = models.PositiveBigIntegerField(validators=[MinValueValidator(7), MaxValueValidator(364)])

    # only admin can change value of this variable
    is_active = models.BooleanField(default=False)
    is_rented = models.BooleanField(default=False)
    pro_city_id = models.IntegerField(blank=True, default=1)
    pro_city_pa_id = models.IntegerField(blank=True, default=2)

    viewed = models.IntegerField(default=24, )

    def __str__(self):
        return 'room ' + self.title


class RoomImage(models.Model):
    room = models.ForeignKey(Room, default=None, on_delete=models.CASCADE, )
    images = models.FileField(upload_to='media/images/rooms/')


class Comment(models.Model):
    comment_user = models.ForeignKey(OwnerUser, on_delete=models.CASCADE, )
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    comment = models.TextField(max_length=350)
    vote = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment_user.full_name + self.comment


class Report(models.Model):
    report_user = models.ForeignKey(OwnerUser, on_delete=models.CASCADE, )
    room = models.ForeignKey(Room, on_delete=models.CASCADE, )
    reason = models.TextField(max_length=350)


class CaredRoom(models.Model):
    user_id = models.ForeignKey(OwnerUser, on_delete=models.CASCADE, )
    room = models.ForeignKey(Room, on_delete=models.CASCADE, )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static '/css/fontawesome.min.css' %}">

{#    <script>#}
{#        $(function() {#}
{#            $("#header").load("header.html");#}
{#            $("#footer").load("footer.html");#}
{#        });#}
{#    </script>#}
    {% block extra_head %}
    {% endblock %}
</head>
<body>
<div id="id_back_top"></div>

{% include "header.html"%}
    <!-- slider -->

{% block content %}
{% endblock %}
{% include "footer.html" %}
</body>
</html>

templates/cared.html
{% for item in cared_roomlist %}
                                    <li class="book_mark_item">
                                            <a class="image" href="/room/{{ item.room.id }}">
                                                <img src="{{ item.room.roomimage_set.all.0.images.url}}">
                                            </a>
                                            <div class="info">
                                                <a href="#" class="title">
                                                    {{ item.room.title}}
                                      <span class="city">{{ item.address}}</span>
                                        </a>
                                                <span class="price">{{ item.room.price}}triệu</span>
                                                <div class="delete">×</div>
                                            </div>
                                        </li>
                                    {% endfor %}

templates/comment_snipset.html
{% load mathfilters %}
<div class="tab_label"><span>Có <strong>{{ comments.count }}</strong> bình luận, đánh giá</span> <strong>về bài đăng</strong>

            </div>
{% for comment in comments %}
                        <div class="_item 931 _level_0 _sub_0">
                        <article itemprop="review" itemscope="" itemtype="http://schema.org/Review">
                            <p class="clearfix cls" itemprop="author" itemtype="http://schema.org/Person">
                                <span class="_avatar">{{ comment.comment_user.full_name.0 }}</span>
                                <span class="_name" itemprop="name">{{ comment.comment_user.full_name }}</span>
                            </p>
                            <div class="_control ">
                                <g-review-stars aria-hidden="true"><span class="Fam1ne tPhRLe" role="img"><span style="width:{{ comment.vote|mul:13 }}px"></span></span>
                                </g-review-stars>
                                <time itemprop="datePublished" content="2020-12-19 22:33" datetime="2020-12-19 22:33" title="2020-12-19 22:33">
                                    {{ comment.time}}</time>
                            </div>
                            <div class="_wrap">
                                <p class="_content " itemprop="description"> {{ comment.comment }}</p>


                            </div>
                        </article>
                    </div>
{% endfor %}

templates/dangky.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
    <link rel="stylesheet" href="/static/css/dangky.css">
{% endblock %}
{% block title %}
    Đăng ký tài khoản
{% endblock %}
{% block content %}
    <div id="header"></div>
    <div class="login_form">
        <div class="title"> Đăng ký </div>
        <div class="form-group">
            <a href="#" class="btn btn-primary btn-block ">
                <i class="fab fa-facebook-f "></i>
                <rb>Đăng ký bằng tài khoản Facebook</rb>
            </a>
        </div>
        <div class="form-group">
            <a href="#" class="btn btn-danger btn-block">
                <i class="fab fa-google text-white"></i> Đăng ký bằng tài khoản Google </a>
            </button>
        </div>
        <div class="text-center"> Hoặc </div>
        <form class="login" method="post">
            {%  csrf_token %}
            <div class="form-group"> {{ form.full_name }}</div>
            <div class=" form-group "> {{ form.username }}</div>
            <div class=" form-group "> {{ form.email }}</div>
            <div class="form-group"> {{ form.phone_number }}</div>
            <div class=" form-group "> {{ form.password1 }} </div>
            <div class=" form-group "> {{ form.password2 }} </div>
            <div class=" form-group "> {{ form.is_owner }} </div>

{#            <div class="form-check-inline">#}
{#                <label class="form-check-label" for="radio1">#}
{#                  <input type="radio" class="form-check-input" id="radio1" name="is_owner" value=0 checked>Người thuê trọ#}
{#                </label>#}
{#            </div>#}
{#            <div class="form-check-inline">#}
{#                <label class="form-check-label" for="radio2">#}
{#                  <input type="radio" class="form-check-input" id="radio2" name="is_owner" value=1>Chủ nhà trọ#}
{#                </label>#}
{#            </div>#}
            <div class="item_message">
                <p class="message text-danger"></p>
            </div>
            <div class="form-group">
                <input type="hidden" name="action" value="register">
                <button class="btnRegister btn btn-warning btn-block btn-lg text-white" type="submit">Đăng ký</button>
            </div>
            <div class="clear"></div>
        </form>
    </div>
    <div class="login_form border-0">
        <div class="form-text">
            <p> Đã có tài khoản? </p>
        </div>
        <div class="form-group">
            <a href="{% url 'login' %}" class="btn btn-outline-dark btn-block font-weight-bold">ĐĂNG NHẬP NGAY</a></div>
    </div>

    <script type="text/javascript" src="{% static 'js/dangky.js' %}"></script>
    <script >
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder="Họ và tên"
        form_fields[2].placeholder="Tên tài khoản*"
        form_fields[3].placeholder="Email*"
        form_fields[4].placeholder="Số điện thoại*"
        form_fields[5].placeholder="Mật khẩu*"
        form_fields[6].placeholder="Nhập lại mật khẩu*"
        for (var field in form_fields)
        {
            form_fields[field].className += ' form-control'
        }
        {% if alert %}
            alert('{{ alert }}');
        {% endif %}
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Trang chủ
{% endblock %}
{% block extra_head %}
    <script src="{% static '/js/test.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
{% endblock %}
{% block content %}
     <!-- end slider -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark searchbar ">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><span class="fas fa-home"></span></a>
            </div>

            <div class="container collapse navbar-collapse" id="navb">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/phongtro/">Phòng trọ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ccmn/">Chung cư mini</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/nnc/">Nhà nguyên căn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ccnc/">Chung cư nguyên căn</a>
                    </li>

                </ul>
                <form class="form-inline my-2 my-lg-0" method="get" id="search-form">
                    {% csrf_token %}
                     <input class="form-control mr-sm-2 ipSeacrh" type="text" name="q" id="id_q" placeholder="Tìm kiếm phòng trọ" >
                    <button class="btn btn-success my-2 my-sm-0" type="submit">Tìm kiếm...</button>
                </form>
            </div>
        </div>
    </nav>
     <!-- end slider -->
    <div class="content container">
        <div class="left-content col-9" id="roomlist">

            <div class="hot-post border-bottom">
                <div class="hot-post_title font-weight-bold my-3">
                    <h4>Cho thuê nhà trọ, cho thuê phòng trọ giá rẻ, tìm nhà trọ, tìm phòng trọ</h4>
                </div>

                <div class="hot-post_content row">
                    {% for item in roomList1 %}
                    <div class="hot-room col">
                        <div class="new-room-img">
                            <a href="/room/{{ item.id }}"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>

                        </div>
                        <div class="basic-info">
                            <a href="/room/{{ item.id }}">{{ item.title|truncatewords_html:6|safe}}</a>
                            <p>Giá: {{ item.price }} triệu đồng/tháng</p>

                        </div>
                        <div class="view">
                         <i class="fa fa-eye"></i>{{ item.viewed }}
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="exp-post" >
                <div class="hot-post_title font-weight-bold my-3">
                    <h5>CHO THUÊ PHÒNG TRỌ</h5>
                </div>
                <ul class="room_post_list">
                    {% for item in roomList2 %}
                    <li class="room_post rp1">
                        <div class="room_post_img">
                            <a href="/room/{{ item.id }}"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>
                        </div>
                        <div class="room_post_content">
                            <p class="price"><span>{{ item.price }} triệu đồng/tháng</span></p>
                            <h3 class="title"><a href="/room/{{ item.id }}">{{ item.title|truncatewords_html:8|safe}}</a></h3>

                            <div class="intro">{{ item.service_charge}}
                            </div>
                            <div class="info1">
                                Địa chỉ :  {{ item.address }}
                            </div>
                            <div class="info2">
                                Gần các địa chỉ: {{ item.nearby }}
                            </div>

                        </div>
                        <div class="view">
                            <i class="fa fa-eye"></i>{{ item.viewed }}
                            </div>
                        <div class="clear"></div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="hot-post_title font-weight-bold my-3">
                    <h5>CHO THUÊ CHUNG CƯ MINI</h5>
                </div>
                <ul class="room_post_list">
                    {% for item in roomList3 %}
                    <li class="room_post rp1">
                        <div class="room_post_img">
                            <a href="/room/{{ item.id }}"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>
                        </div>
                        <div class="room_post_content">
                            <p class="price"><span>{{ item.price }} triệu đồng/tháng</span></p>
                            <h3 class="title"><a href="/room/{{ item.id }}">{{ item.title|truncatewords_html:8|safe}}</a></h3>

                            <div class="intro">{{ item.service_charge}}
                            </div>
                            <div class="info1">
                                Địa chỉ :  {{ item.address |truncatewords_html:8|safe}}
                            </div>
                            <div class="info2">
                                Gần các địa chỉ: {{ item.nearby }}
                            </div>

                        </div>
                        <div class="view">
                            <i class="fa fa-eye"></i>{{ item.viewed }}
                            </div>
                        <div class="clear"></div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="hot-post_title font-weight-bold my-3">
                    <h5>CHO THUÊ NHÀ NGUYÊN CĂN</h5>
                </div>
                <ul class="room_post_list">
                    {% for item in roomList4 %}
                    <li class="room_post rp1">
                        <div class="room_post_img">
                            <a href="/room/{{ item.id }}"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>
                        </div>
                        <div class="room_post_content">
                            <p class="price"><span>{{ item.price }} triệu đồng/tháng</span></p>
                            <h3 class="title"><a href="/room/{{ item.id }}">{{ item.title|truncatewords_html:8|safe}}</a></h3>

                            <div class="intro">{{ item.service_charge}}
                            </div>
                            <div class="info1">
                                Địa chỉ :  {{ item.address |truncatewords_html:8|safe}}
                            </div>
                            <div class="info2">
                                Gần các địa chỉ: {{ item.nearby }}
                            </div>

                        </div>
                        <div class="view">
                            <i class="fa fa-eye"></i>{{ item.viewed }}
                            </div>
                        <div class="clear"></div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="hot-post_title font-weight-bold my-3">
                     <h5>CHO THUÊ CHUNG CƯ NGUYÊN CĂN</h5>
                </div>
                <ul class="room_post_list">
                    {% for item in roomList5 %}
                    <li class="room_post rp1">
                        <div class="room_post_img">
                            <a href="/room/{{ item.id }}"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>
                        </div>
                        <div class="room_post_content">
                            <p class="price"><span>{{ item.price }} triệu đồng/tháng</span></p>
                            <h3 class="title"><a href="/room/{{ item.id }}">{{item.title|truncatewords_html:8|safe}}</a></h3>

                            <div class="intro">{{ item.service_charge}}
                            </div>
                            <div class="info1">
                                Địa chỉ :  {{ item.address |truncatewords_html:8|safe}}
                            </div>
                            <div class="info2">
                                Gần các địa chỉ: {{ item.nearby }}
                            </div>

                        </div>
                        <div class="view">
                            <i class="fa fa-eye"></i>{{ item.viewed }}
                            </div>
                        <div class="clear"></div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="right-content col-3">
            <div class="right_title my-3">
                <h4>PHÒNG TẠI HÀ NỘI</h4>
            </div>
            <ul class="right_room_list">
                {% for item in hanoi_roomlist %}
                <li class="rr_post">
                    <a href="/room/{{ item.id }}" class="img"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>
                    <a href="/room/{{ item.id }}" class="title">{{ item.title|truncatewords_html:8|safe}}</a>
                    <p class="price">{{ item.price}}</p>
                    <div class="clear"></div>

                </li>
                {% endfor %}

            </ul>
        </div>
    </div>
    <script>
    document.getElementById("id_q").value="{{ query }}";
            $("#search-form").submit(function(e) {
                            e.preventDefault();

                            $.ajax({
                                type:'GET',
                                url:'',
                                data:{

                                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                                    q:$('#id_q').val(),
                                },
                                success: function(response){
                                    $('#id_q').val('')
                                    $('#roomlist').html(response)

                                {#$("#comment_list").append(temp);#}

                                },
                                error: function(response){
                                    alert("good bye");
                                },
                            })

                        })
    {#$(document).ready(function(){#}
  // $("#myInput").on("keyup", function() {
  //   var value = $(this).val().toLowerCase();
  //   $(".room_post").filter(function() {
  //     $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
  //   });
  // });

{#  var x ="";#}
{##}
{##}
{#  $(".dropdown-item").on("click",function(){#}
{##}
{##}
{##}
{##}
{#    $(this).addClass("active");#}
{#    x = $(".active").text();#}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{#  })#}
{##}
{##}
{##}
{##}
{##}
{#  $("#search-btn").on("click",function(e){#}
{#    x+=" "  + $("#myInput").val().toLowerCase();#}
{#    alert(x);#}
{#    e.preventDefault();#}
{#    $.ajax({#}
{#        type:'GET',#}
{#        url:'',#}
{#        data:{#}
{##}
{#            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),#}
{#            q:x,#}
{#        },#}
{#        success: function(response){#}
{#            $('#id_q').val('')#}
{#            alert('hello');#}
{#            $('#roomlist').html(response)#}
{##}
        {#$("#comment_list").append(temp);#}
{##}
{#        },#}
{#        error: function(response){#}
{#            alert("good bye");#}
{#        },#}
{#    })#}
{#    x="";#}
{##}
{##}
{#  })#}
{#});#}
    </script>


{% endblock %}

templates/posttest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dang phong</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">
        Dang phong
    </button>
</form>
</body>
</html>

templates/roomListse.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

    Trang chủ
{% endblock %}
{% block extra_head %}
    <script src="{% static '/js/test.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
    <div class="hot-post_title">
                    Danh sách phòng tại {{ad}}
                </div>
                <ul class="room_post_list">
                    {% for item in roomlist %}
                    <li class="room_post rp1">
                        <div class="room_post_img">
                            <a href="/room/{{ item.id }}"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>
                        </div>
                        <div class="room_post_content">
                            <p class="price"><span>{{ item.price }} triệu đồng/tháng</span></p>
                            <h3 class="title"><a href="/room/{{ item.id }}">{{ item.title|truncatewords_html:8|safe}}</a></h3>

                            <div class="intro">{{ item.service_charge}}
                            </div>
                            <div class="info1">
                                Địa chỉ :  {{ item.address }}
                            </div>
                            <div class="info2">
                                Gần các địa chỉ: {{ item.nearby }}
                            </div>
                            <i class="fa fa-eye"></i>{{ item.viewed }}
                        </div>
                        <div class="clear"></div>
                    </li>
                    {% endfor %}
                </ul>
    </div>
{% endblock %}

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="search-bar">
        <form action="">
            <input  class="input_seacrh">
            <button>Tim kiem</button>
        </form>
        
    </div>
</body>
</html>

templates/serach_snipset.html
                <div class="box-header">
            <h1 class="box-title text-left">Khu vực nổi bật</h1>
        </div>
        <div class="box-body">
            <div class="row quick_search">
                <div class="col-md-6 pr-0">
                    <div class="item hcm" style="background-image: url('https://tromoi.com/frontend/home/images/thanh-pho/ho-chi-minh.jpg');">
                        <a href="hcm">Hồ Chí Minh <span></span></a>
                    </div>
                </div>
                <div class="col-md-6 ">
                    <div class="row hn">
                        <div class="col-md-6 px-1 pb-1">
                            <div class="item" style="background-image: url('https://tromoi.com/frontend/home/images/thanh-pho/ha-noi.jpg');">
                                <a href="/hn/">Hà Nội <span></span></a>
                            </div>
                        </div>
                        <div class="col-md-6 pl-0 pb-1">
                            <div class="item" style="background-image: url('https://tromoi.com/frontend/home/images/thanh-pho/thua-thien-hue.jpg');">
                                <a href="/hue/">Thừa Thiên Huế <span></span></a>
                            </div>
                        </div>
                    </div>
                    <div class="row hn">
                        <div class="col-md-6 px-1">
                            <div class="item " style="background-image: url('https://tromoi.com/frontend/home/images/thanh-pho/da-nang.jpg');">
                                <a href="/danang/">Đà Nẵng <span></span></a>
                            </div>
                        </div>
                        <div class="col-md-6 pl-0">
                            <div class="item " style="background-image: url('https://tromoi.com/frontend/home/images/thanh-pho/can-tho.jpg');">
                                <a href="/cantho/">Cần Thơ <span></span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                    {% if not searched %}
                    <div class="hot-post_title">
                    Không tìm thấy kết quả
                    </div>

                {% else %}
                <div class="hot-post_title">
                    Danh sách phòng theo yêu cầu tìm kiếm
                </div>
                <ul class="room_post_list">
                    {% for item in searched %}
                    <li class="room_post rp1">
                        <div class="room_post_img">
                            <a href="/room/{{ item.id }}"><img src="{{ item.roomimage_set.all.0.images.url }}" alt=""></a>
                        </div>
                        <div class="room_post_content">
                            <p class="price"><span>{{ item.price }} triệu đồng/tháng</span></p>
                            <h3 class="title"><a href="/room/{{ item.id }}">{{ item.title|truncatewords_html:8|safe}}</a></h3>

                            <div class="intro">{{ item.service_charge}}
                            </div>
                            <div class="info1">
                                Địa chỉ :  {{ item.address }}
                            </div>
                            <div class="info2">
                                Gần các địa chỉ: {{ item.nearby }}
                            </div>

                        </div>
                        <div class="view">
                         <i class="fa fa-eye"></i>{{ item.viewed }}
                        </div>
                        <div class="clear"></div>
                    </li>
                    {% endfor %}
                </ul>
            {% endif %}